# services:
#   server:
#     build:
#       context: ./
#       dockerfile: ./packages/server/Dockerfile
#     env_file:
#       - ./packages/server/.env
#     depends_on:
#       - db
#   db:
#     image: postgres:latest
#     ports:
#       - '5432:5432'
#     env_file:
#       - ./packages/server/.env
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: mydb_development
#     volumes:
#       - ./docker/postgres:/var/lib/postgresql/data
